package marco.demos.pam.mydemopam;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String requestorName;
	private int requestorAge;
	private int amount;
	private java.lang.String message;
	private boolean accepted;

	public RequestData() {
	}

	public java.lang.String getRequestorName() {
		return this.requestorName;
	}

	public void setRequestorName(java.lang.String requestorName) {
		this.requestorName = requestorName;
	}

	public int getRequestorAge() {
		return this.requestorAge;
	}

	public void setRequestorAge(int requestorAge) {
		this.requestorAge = requestorAge;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public boolean isAccepted() {
		return this.accepted;
	}

	public void setAccepted(boolean accepted) {
		this.accepted = accepted;
	}

	public RequestData(java.lang.String requestorName, int requestorAge,
			int amount, java.lang.String message, boolean accepted) {
		this.requestorName = requestorName;
		this.requestorAge = requestorAge;
		this.amount = amount;
		this.message = message;
		this.accepted = accepted;
	}

}