package marco.demos.dm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String requestorName;
	private int requestorAge;
	private int amount;

	public RequestData() {
	}

	public java.lang.String getRequestorName() {
		return this.requestorName;
	}

	public void setRequestorName(java.lang.String requestorName) {
		this.requestorName = requestorName;
	}

	public int getRequestorAge() {
		return this.requestorAge;
	}

	public void setRequestorAge(int requestorAge) {
		this.requestorAge = requestorAge;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public RequestData(java.lang.String requestorName, int requestorAge,
			int amount) {
		this.requestorName = requestorName;
		this.requestorAge = requestorAge;
		this.amount = amount;
	}

}